### ISSUE TITLE
notes on current commit of AtomSpaceExplorer

### ISSUE THREAD

**Issue by mjsduncan** [opencog/external-tools#100]
this is a mix of comments, bugs & TODOs based on hooking up the ase to an atomspace being used for the biology project mozi.

there needs to be a cap on the number of atoms to load:  my first try was on an atomspace with 4 million nodes and it tried to load them all, filling up ram and then bogging down filling up swap disk!  i had to shut down the cogserver to get it to stop.  maybe this is more of an opencog rest api problem.

when i went to to reload the atomspace by pressing `fetch` either no nodes appear or there is part of a node stuck in the upper left corner behind the `play` button.  i have to close the tab and open a new one to get a new dump from the atomspace.

it would be nice to have the history list back in the url line so i don't have to keep retyping the url!

the url is `http://localhost:5000/api/v1.1/atoms` and after the first time entered, when i retype and get to the "v" the version window pops up as if i typed `control-v`.

i successfully loaded an atomspace of 115 atoms from an ensemble of moses models.  the repulsion force ends up squashing almost everything against the edges of the window.  can the boundaries be made repulsive as well to spread everything out in the space?

let me know what else i can test or what info you need to improve feedback.

thanks!

**Comment by mjsduncan** [comment]
this is on firefox 56.0 for ubuntu

**Comment by mjsduncan** [comment]
also changing the language doesn't change the tool-tip language.

**Comment by sshermz** [comment]
Thanks for the testing and feedback. Please enter separate issues or enhancement requests for each item (For latter, just prepend "enhancement request: " to the issue title. I.E. The history list request is an enh. request).

For the performance issue, please provide your 115 atoms scm file (or a json file).

**Comment by AmeBel** [comment]
FYI, there is an `enhancement` label

**Comment by sshermz** [comment]
Perfect. Thanks @AmeBel.
