### ISSUE TITLE
fetch only works correctly on first application

### ISSUE THREAD

**Issue by mjsduncan** [opencog/external-tools#102]
when i went to to reload the atomspace by pressing fetch either no nodes appear or there is part of a node stuck in the upper left corner behind the play button. i have to close the tab and open a new one to get a new dump from the atomspace.

**Comment by sshermz** [comment]
Your first fetch failed and left ASE in a bad state. So the actual bug is that ASE doesn't fail gracefully when unable to load data successfully from a fetch. 

Please retest with latest version ( pull request #106 ). Is it still reproducible?

**Comment by mjsduncan** [comment]
i think that fixed it, thanks!
