### ISSUE TITLE
Invalid atom syntax (SUMO)

### ISSUE THREAD

**Issue by manisabri** [opencog/external-tools#128]
I get a syntax error when I try to import likes of below implication rule from SUMO to Atomspace

```
(=>
  (and
     (domain ?REL ?NUMBER ?CLASS1)
     (domain ?REL ?NUMBER ?CLASS2))
  (or
     (subclass ?CLASS1 ?CLASS2)
     (subclass ?CLASS2 ?CLASS1))
)
```

ERROR: In procedure cog-new-link:
Throw to key `C++-EXCEPTION' with args `("cog-new-link" "Invalid Atom syntax: 

(OrLink
  (InheritanceLink
    (VariableNode \"?CLASS1\") ; [49929d9688eabc67][1]
    (VariableNode \"?CLASS2\") ; [1bdad0b3e1d92a86][1]
  ) ; [ea88a87e2b7f8980][1]
  (InheritanceLink
    (VariableNode \"?CLASS2\") ; [1bdad0b3e1d92a86][1]
    (VariableNode \"?CLASS1\") ; [49929d9688eabc67][1]
  ) ; [f6134a8c23788e31][1]
) ; [d80ddb80465d3195][-1] (/opncog/atomspace/opencog/atoms/base/ClassServer.cc:138)
Function args:
((InheritanceLink
   (VariableNode \"?CLASS1\")
   (VariableNode \"?CLASS2\")
)
 (InheritanceLink
   (VariableNode \"?CLASS2\")
   (VariableNode \"?CLASS1\")
)
)")'.

It's about the consequent of the implication rule.
I'll be happy to fix it but I'm still very new to the whole thing
Creating the whole OrLink in guile throws the same exception, is something wrong with this syntax?

**Comment by linas** [comment]
try grabbing the latest version of teh atomspace. @ngeiswei very recently changed something that I think might fix this.
