### ISSUE TITLE
Connect button disabled in AtomViewer

### ISSUE THREAD

**Issue by GarethNelson** [opencog/external-tools#47]
Not sure why, but it was commented out here and uncommenting it doesn't help (i.e it's completely broken):

https://github.com/opencog/external-tools/commit/59990f86a789a93cce77e0468b4a4a3f0258a649

**Comment by GarethNelson** [comment]
It should be noted that uncommenting and clicking the button does precisely nothing (no requests are made to cogserver)

**Comment by skoumas** [comment]
May I know the browser you are using please as well making sure that you are running the latest version at the ocViewer folder? Thank you...

**Comment by AmeBel** [comment]
@GarethNelson a newer version been merged to master, so please update your clone before checking

**Comment by TScottJ** [comment]
AtomViewer has been obsoleted. We're putting up a new visualizer, AtomSpaceExplorer, very soon.
