### ISSUE TITLE
Please bring back ability to specify port # for glimpse atomspace viewer

### ISSUE THREAD

**Issue by eddiemonroe** [opencog/external-tools#68]
You used to be able to specify the port # the app would listen to with the startup command, e.g., 

    ./startServer.sh 9000   #for port 9000

But with the recent change in the startup command, it looks like you can no longer do this.

This is important especially because the default port for the glimpse app (8000) conflicts with a port used by the Hanson Robotics HEAD stack for it's web user interface (also 8000). Perhaps we should also change the default port for the atomspace viewer.

**Comment by eddiemonroe** [comment]
The port number can be manually changed in index.js, but would be good to be able to do this via the startup command like before.

**Comment by TScottJ** [comment]
Hey Eddie, we are adding a new version of the visualizer soon, called AtomSpaceExplorer, which is based off the Mozi_visualizer (which was based off glimpse). So we'll apply this issue to that one, and see if we can enable the port # feature.

**Comment by eddiemonroe** [comment]
Great, thanks, Scott.

**Comment by sshermz** [comment]
@eddiemonroe , the AtomSpace Explorer is available now in external-tools (https://github.com/opencog/external-tools/tree/master/AtomSpaceExplorer). You can override the default port 4200 as follows (this is copy/paste of an update to the AtomSpace Explorer README.md that I'll commit in my next set of updates):

npm start                           # Start the app on the default AngularJS port 4200.

npm start -- --port=<port-number>   # Start the app at <port-number>.
npm start -- --port=8080            # Example with port number 8080.

Alternatively, you can permanently change the default port by inserting the following to angular-cli.json, at the top of the "defaults" block:
  "defaults": {                     #    Existing line.
    "serve": {                      # <- Inserted line.
      "port": 8080                  # <- Inserted line. Example port 8080. Set port number as desired.
    },                              # <- Inserted line.
    "styleExt": "css",              #    Existing line.
