### ISSUE TITLE
notes on updating node package versions for AtomSpaceExplorer

### ISSUE THREAD

**Issue by mjsduncan** [opencog/external-tools#97]
the web interface looks great!  if/when versioning becomes an becomes an issue, here are some TODOs:

name change from `angular-cli` to `@angular/cli` in [karma.conf.js](https://github.com/opencog/external-tools/blob/master/AtomSpaceExplorer/karma.conf.js) lines 7 and 12.

the `MaterialModule` is no longer in `@angular/material`.  individual components have to be imported explicitly or a group of components can be defined to import.  see discussion [here](https://stackoverflow.com/questions/45166844/how-to-import-angular-material-in-project).  in [app.module.ts](https://github.com/opencog/external-tools/blob/master/AtomSpaceExplorer/src/app/app.module.ts#L5) and [auth.module.ts](https://github.com/opencog/external-tools/blob/master/AtomSpaceExplorer/src/app/core/auth/auth.module.ts#L8).

... ???

**Comment by sshermz** [comment]
@mjsduncan , I've done a major packages update in my pull request #98. Thanks for the tips which were quite helpful!

**Comment by mjsduncan** [comment]
cool, glad they turned out to be useful!
